ENH: Add animations notebooks
knightlab-analyses/american-gut-analyses pull request #6
Opened 2017-07-25 01:31 UTC by ElDeveloper

I have not included the data as GitHub rejected my commits due to exceeding file size.

2017-07-25 03:58 UTC, wasade commented
Okay thanks, can you send file paths relative to barnacle via email? We can
stage on ftp

On Jul 24, 2017 6:31 PM, "Yoshiki Vázquez Baeza" <notifications@github.com>
wrote:

I have not included the data as GitHub rejected my commits due to exceeding
file size.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/knightlab-analyses/american-gut-analyses/pull/6
Commit Summary

   - ENH: Add animations notebooks

File Changes

   - *A* ipynb/Animations (metadata curation).ipynb
   <https://github.com/knightlab-analyses/american-gut-analyses/pull/6/files#diff-0>
   (205)
   - *A* ipynb/Animations (processing).ipynb
   <https://github.com/knightlab-analyses/american-gut-analyses/pull/6/files#diff-1>
   (149)

Patch Links:

   - https://github.com/knightlab-analyses/american-gut-
   analyses/pull/6.patch
   - https://github.com/knightlab-analyses/american-gut-analyses/pull/6.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/knightlab-analyses/american-gut-analyses/pull/6>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AAc8svltno29MmzZbuXlv0ByOEoLBFdXks5sRUWEgaJpZM4Oh9KM>
.

2017-07-25 23:46 UTC, ElDeveloper commented
All the data can be found here: 

/home/yovazquezbaeza/research/ag-animation/data-for-animations

2017-07-25 23:50 UTC, wasade requested changes
mostly minor

2017-07-25 23:50 UTC, wasade commented on ipynb/Animations (metadata curation).ipynb
> +    "Download the mapping files for the ICU, ITS and FMT from Qiita. Then combine them with the AG mapping file that you got from Justine."
Would it be possible to indicate the study IDs?

2017-07-25 23:50 UTC, wasade commented on ipynb/Animations (metadata curation).ipynb
> +    "Download the mapping files for the ICU, ITS and FMT from Qiita. Then combine them with the AG mapping file that you got from Justine."
@jwdebelius, can you clarify which mapping file this is? Let me know if more things need to be staged on the ftp

2017-07-25 23:50 UTC, wasade commented on ipynb/scripts/expand.py
> +This script is courtesy of Dr. Daniel McDonald, originally found in:
maybe link [here](https://github.com/wasade/reimagined-fiesta) instead of barnacle?

2017-07-25 23:50 UTC, wasade commented on ipynb/scripts/make-representative-sequences.py
> +bt = q2.Artifact.load('deblur-ag/table.qza').view(Table)
i believe this is one of the files that will need to be on the ftp?

2017-07-25 23:50 UTC, wasade commented on ipynb/scripts/remove-blooms.py
> +bt = q2.Artifact.load('deblur-fmt-and-icu/table.qza').view(Table)
same?

2017-07-25 23:50 UTC, wasade commented on ipynb/scripts/remove-blooms.py
> +with open('newbloom.all.fna', 'r') as f:
possible to add a comment noting the source? 

https://github.com/knightlab-analyses/bloom-analyses/blob/master/data/newbloom.all.fna

2017-07-25 23:50 UTC, wasade commented on ipynb/scripts/remove-blooms.py
> +blooms = [b[:125] for b in blooms]
possible to add a comment noting that this is the trim length used for the manuscript as one sequencing round was at 125 cycles?

2017-07-25 23:50 UTC, wasade commented on ipynb/Animations (processing).ipynb
> +    "* ICU (work with Paul Wischmeyer).\n",
qiita study IDs?

2017-07-25 23:50 UTC, wasade commented on ipynb/Animations (processing).ipynb
> +    "qsub -l mem=128gb,nodes=1:ppn=32 -l walltime=120:00:00 -e sortmerna.e -o sortmerna.o -N closed commands.sh\n",
maybe remove the `qsub` as that isn't actually necessary here?

2017-07-25 23:50 UTC, wasade commented on ipynb/Animations (processing).ipynb
> +    "qsub -l mem=128gb,nodes=1:ppn=32 -l walltime=120:00:00 -e sortmerna.e -o sortmerna.o -N closed commands.sh\n",
same

2017-07-26 01:29 UTC, jwdebelius commented on ipynb/Animations (metadata curation).ipynb
> +    "Download the mapping files for the ICU, ITS and FMT from Qiita. Then combine them with the AG mapping file that you got from Justine."
This needs the full mapping file. I'll send it to you.

2017-07-26 17:54 UTC, ElDeveloper commented on ipynb/scripts/make-representative-sequences.py
> +bt = q2.Artifact.load('deblur-ag/table.qza').view(Table)
I think we don't need to do this, as this file will be generated by the commands in the notebook.

2017-07-26 17:54 UTC, ElDeveloper commented on ipynb/scripts/remove-blooms.py
> +bt = q2.Artifact.load('deblur-fmt-and-icu/table.qza').view(Table)
This file is also generated by the commands in the notebook.

2017-07-26 17:55 UTC, ElDeveloper commented on ipynb/scripts/remove-blooms.py
> +with open('newbloom.all.fna', 'r') as f:
This file should be downloaded via the notebook, I'll note this in the comments.

2017-07-26 17:57 UTC, ElDeveloper commented on ipynb/scripts/remove-blooms.py
> +blooms = [b[:125] for b in blooms]
For sure!

2017-07-26 17:58 UTC, ElDeveloper commented on ipynb/Animations (processing).ipynb
> +    "* ICU (work with Paul Wischmeyer).\n",
Added, including links to the papers.

2017-07-26 17:58 UTC, ElDeveloper commented on ipynb/Animations (processing).ipynb
> +    "qsub -l mem=128gb,nodes=1:ppn=32 -l walltime=120:00:00 -e sortmerna.e -o sortmerna.o -N closed commands.sh\n",
Sounds good.

2017-07-26 17:59 UTC, ElDeveloper commented on ipynb/Animations (processing).ipynb
> +    "qsub -l mem=128gb,nodes=1:ppn=32 -l walltime=120:00:00 -e sortmerna.e -o sortmerna.o -N closed commands.sh\n",
👍

2017-07-26 17:59 UTC, ElDeveloper commented on ipynb/scripts/expand.py
> +This script is courtesy of Dr. Daniel McDonald, originally found in:
This script now points to that repo and notes the modifications I made.

2017-07-26 21:16 UTC, wasade commented
would it be possible to make an `ipynb/animation` or something like that directory, and to migrate these to that?

2017-07-26 23:51 UTC, ElDeveloper commented
@wasade makes sense! Just did that!

2017-08-01 17:06 UTC, wasade approved these changes

2017-08-01 17:06 UTC, merged

2017-08-01 17:07 UTC, ElDeveloper commented
Thanks!

On (Aug-01-17|10:06), Daniel McDonald wrote:
> Merged #6.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/knightlab-analyses/american-gut-analyses/pull/6#event-1188052928