Balance notebooks
knightlab-analyses/american-gut-analyses pull request #8
Opened 2017-07-25 20:49 UTC by mortonjt

This is merging #3 #4 and #5 together

2017-07-25 21:46 UTC, wasade commented
Thanks! Reviewing now

2017-07-25 23:05 UTC, wasade requested changes
Mostly just documentation revisions but some code questions too

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "Here we will investigate the country differences within the microbial communities.  Here we will use Ward hierarchical clustering to identify very obvious patterns.  This method trys to identify
Here we will investigate differences in human gut microbial communities mediated by country.  We will use Ward hierarchical clustering to identify any obvious patterns, combined with Balance Trees, which tries to identify maximum variance partitions. Following this, we will run a linear regression in order to investigate whether the balances between highly variable subcommunities can be explained using the variables that have measured.

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "Now we will run the qiime2 analyses to generate the balances and run the linear regression.  Remember, ANOVA is a type of linear regression, so we can test for differientially abundant balances
Now we will run the qiime2 analyses to generate the balances and compute ANOVA, a type of linear regression,  to test for differentially abundant balances.

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "Here we will investigate the country differences within the microbial communities.  Here we will use Ward hierarchical clustering to identify very obvious patterns.  This method trys to identify
May also be worth adding a hyperlink to the paper on balances

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "otu_table=deblur_125nt_no_blooms_rare.biom\n",
shouldn't this all be a code cell with the qiime commands prefixed by `!`?

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "    'deblur_125nt_no_blooms_rare.biom.tree.nwk.qza').view(TreeNode)\n",
should this be pulled from the ftp as well?

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "        return 'denominator'\n",
given the conditional, shouldn't this return `"denominator"`?

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "For the purposes of plotting the balances, we'll want to exclude countries that aren't the US, UK or Canada.\n",
"...because these were the only countries with more than 100 samples following the filtering noted in the supplemental."

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "We'll also want to refer to the USA as the United States."
"...for visualization purposes."

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "# #16295b blue United Kingdom\n",
two different blues for the UK?

2017-07-25 23:05 UTC, wasade commented on ipynb/country-balance-analysis.ipynb
> +    "plt.savefig('country.pdf')"
figure in manuscript has the ylim from around (-17, 0), this looks like its inverted?

2017-07-25 23:05 UTC, wasade commented on ipynb/types-of-plants-balances.ipynb
> +    "Make sure that the appropriate files are downloaded.  They can be obtained from the ftp link using the following commands\n",
can you create an issue and assign to me noting the specific files which are missing, and to tie the issue to any affected notebook so i can issue an appropriate PR later with the URLs?

2017-07-25 23:05 UTC, wasade commented on ipynb/types-of-plants-balances.ipynb
> +    "We will only analyze samples from a small subset -- specifically those samples that only have metabolics samples."
metabolomics

2017-07-25 23:05 UTC, wasade commented on ipynb/types-of-plants-balances.ipynb
> +    "#table = table.filter(var_filter, axis='observation')\n",
if this isn't used can the line be removed (and the corresponding binding of `var_filter`)?

2017-07-25 23:05 UTC, wasade commented on ipynb/types-of-plants-balances.ipynb
> +    "We'll perform some relaxed filters to remove sequences that are likely not interesting."
"...as they are low in abundance across samples."

2017-07-25 23:05 UTC, wasade commented on ipynb/types-of-plants-balances.ipynb
> +    "table = table.loc[:, clf.feature_importances_>0.004]"
what's `0.004`?

2017-07-25 23:05 UTC, wasade commented on ipynb/types-of-plants-balances.ipynb
> +    "From here, we can see that there some differences between clade with respect to plant diet."
"clade" -> "clades"

2017-07-25 23:05 UTC, wasade commented on ipynb/urban-rural-balance-analysis.ipynb
> +    "Here we will be analyzing the urban / rural data using balances on a phylogeny.  Specifically, we will be constructing our balances from a phylogeny, and run linear regression to test for specif
making a note to revise the references in the manuscript on this, but it is not an urban vs. rural comparison. this is an urban vs. traditional lifestyle

2017-07-25 23:05 UTC, wasade commented on ipynb/urban-rural-balance-analysis.ipynb
> +    "Here we will be analyzing the urban / rural data using balances on a phylogeny.  Specifically, we will be constructing our balances from a phylogeny, and run linear regression to test for specif
Here we will be analyzing the urban/rural vs. traditional lifestyle data using balances based on a phylogeny.  Specifically, we will be constructing our balances from a phylogeny, and run a linear regression to test for specific microbial evolutionary divergences that could explain the differences between traditional lifestyles and rural/urban populations.

2017-07-25 23:05 UTC, wasade commented on ipynb/urban-rural-balance-analysis.ipynb
> +    "A couple of balances that appear to interesting as noted as y46 and y463.  Let's investigate those balances in more detail."
not obvious why these are interesting given the output above

2017-07-25 23:05 UTC, wasade commented on ipynb/urban-rural-balance-analysis.ipynb
> +    "'Spirochaetaceae': ctable[list(tree.find('y46').children[NUMERATOR].subset())].sum(axis=1),\n",
how were the taxons determined?

2017-07-25 23:05 UTC, wasade commented on ipynb/urban-rural-balance-analysis.ipynb
> +    "From here, we can see that there are a few interesting clades that can explain the differences between the urban, rural and hunter and gather groups."
"between the urban/rural population and the traditional lifestyles."

2017-07-26 01:34 UTC, jwdebelius commented on ipynb/country-balance-analysis.ipynb
> +    "    'deblur_125nt_no_blooms_rare.biom.tree.nwk.qza').view(TreeNode)\n",
We don't have the artifacts on the FTP. We have the raw data (text, biom, .tree)

2017-07-26 01:40 UTC, wasade commented
I'm adding

On Jul 25, 2017 18:34, "Justine Debelius" <notifications@github.com> wrote:

> *@jwdebelius* commented on this pull request.
> ------------------------------
>
> In ipynb/country-balance-analysis.ipynb
> <https://github.com/knightlab-analyses/american-gut-analyses/pull/8#discussion_r129465330>
> :
>
> > +     "name": "stderr",
> +     "output_type": "stream",
> +     "text": [
> +      "/Users/mortonjt/miniconda3/envs/bio/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (0,66) have mixed types. Specify dtype option on import or set low_memory=False.\n",
> +      "  interactivity=interactivity, compiler=compiler, result=result)\n"
> +     ]
> +    }
> +   ],
> +   "source": [
> +    "mapping = pd.read_table('ag_map_with_alpha.txt', index_col=0)\n",
> +    "\n",
> +    "table = load_table('deblur_125nt_no_blooms.biom')\n",
> +    "balances = qiime2.Artifact.load(\n",
> +    "    'deblur_125nt_no_blooms_rare.biom.balances.qza').view(pd.DataFrame)\n",
> +    "tree = qiime2.Artifact.load(\n",
> +    "    'deblur_125nt_no_blooms_rare.biom.tree.nwk.qza').view(TreeNode)\n",
>
> We don't have the artifacts on the FTP. We have the raw data (text, biom,
> .tree)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/knightlab-analyses/american-gut-analyses/pull/8#discussion_r129465330>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAc8siNL8lY3sWtWfSN6d3_mvlcGxUMOks5sRpeggaJpZM4OjG_u>
> .
>

2017-07-26 20:57 UTC, wasade commented on ipynb/urban-rural-balance-analysis.ipynb
> +    "table = load_table('meta_urban_rural.biom')\n",
is this the rarefied or unrarefied table? i don't recognize this filename

2017-07-26 21:04 UTC, mortonjt commented
In this case - unrarified.  Is there a preference?  We can swap out pretty
easily

On Wed, Jul 26, 2017 at 1:57 PM, Daniel McDonald <notifications@github.com>
wrote:

> *@wasade* commented on this pull request.
> ------------------------------
>
> In ipynb/urban-rural-balance-analysis.ipynb
> <https://github.com/knightlab-analyses/american-gut-analyses/pull/8#discussion_r129694161>
> :
>
> > +  },
> +  {
> +   "cell_type": "markdown",
> +   "metadata": {},
> +   "source": [
> +    "We'll import the data and parse out the taxonomy.  The phylogeny tree is rather large, so we'll prune it down to make it a little more managable."
> +   ]
> +  },
> +  {
> +   "cell_type": "code",
> +   "execution_count": 2,
> +   "metadata": {},
> +   "outputs": [],
> +   "source": [
> +    "metadata = pd.read_table('mapping_meta_urban_rural.txt', index_col=0)\n",
> +    "table = load_table('meta_urban_rural.biom')\n",
>
> is this the rarefied or unrarefied table? i don't recognize this filename
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/knightlab-analyses/american-gut-analyses/pull/8#pullrequestreview-52495502>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AD_a3fsiyrjtDqLsFkHXUCBF66mvMG8cks5sR6hMgaJpZM4OjG_u>
> .
>

2017-07-28 08:43 UTC, mortonjt commented
Closing this in favor of #14

2017-07-28 08:43 UTC, closed without merging