vioscreen comparison notebooks
knightlab-analyses/american-gut-analyses pull request #9
Opened 2017-07-25 21:33 UTC by serenejiang

2017-07-25 23:11 UTC, wasade requested changes

2017-07-25 23:11 UTC, wasade commented on ipynb/vioscreen_comparisons.ipynb
> +{
Could you add some documentation cells to guide a reader as to what's going on?

2017-07-25 23:11 UTC, wasade commented on ipynb/vioscreen_comparisons.ipynb
> +    "mapping = pd.read_csv('viscreen_subsample_mapping.txt', sep='\\t') "
can you clarify where this file originated from? @jwdebelius do you know?

2017-07-25 23:11 UTC, wasade commented on ipynb/vioscreen_comparisons.ipynb
> +       "      <td>10317.000040</td>\n",
i'm concerned that these sample IDs are truncated. can this notebook be rerun using data that are not truncated to verify the results dont change?

2017-07-27 18:20 UTC, jwdebelius commented on ipynb/vioscreen_comparisons.ipynb
> +    "mapping = pd.read_csv('viscreen_subsample_mapping.txt', sep='\\t') "
This was the map we filtered to use only the vioscreen samples, right? Can we do that filtering here, in the notebook?

2017-08-01 20:46 UTC, serenejiang commented on ipynb/vioscreen_comparisons.ipynb
> +{
sure! Just Add in the new version.

2017-08-01 20:46 UTC, serenejiang commented on ipynb/vioscreen_comparisons.ipynb
> +    "mapping = pd.read_csv('viscreen_subsample_mapping.txt', sep='\\t') "
Yes, Justine. You are right. I also include the detailed code for filtering in the new notebook.

2017-08-01 20:53 UTC, serenejiang commented on ipynb/vioscreen_comparisons.ipynb
> +       "      <td>10317.000040</td>\n",
In fact, I didn't use the Sample ID in the analysis. But I just re-run the result to make sure it is not affected.

2017-08-02 16:18 UTC, wasade approved these changes

2017-08-02 16:18 UTC, merged